cdntools:
    build: .
    ports:
     - "8032:80"
    environment:
       SERVICE_80_NAME: http
       SERVICE_NAME: cdntools
       SERVICE_TAGS: production
    volumes:
     - "~/.cdn-tools:/var/www/fuelphp/fuel/app/config/production"

