services:
  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=cdn_user
      - MYSQL_DATABASE=cdn_tools
      - MYSQL_PASSWORD=cdn_password
    ports:
      - 55006:3306
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=cdn_user
      - DB_DATABASE=cdn_tools
      - DB_PASSWORD=cdn_password
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mariadb
    ports:
      - 50000:80
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  mariadb_data: