cdntools:
    build: .
    ports:
     - "80:80"
    environment:
       SERVICE_80_NAME: http
       SERVICE_NAME: cdntools
       SERVICE_TAGS: production
#   volumes:
#    - "/docker-volumes/cdn-tools/config:/var/www/fuelphp/fuel/app/config"
#
